name: 'Commit check using commitizen'
description: 'Create a commit check'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  range:
    description: 'Commit Ranges for checking'
    required: false
